import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sidebar from "../components/Sidebar";

// Load custom fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// SEO Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout structure
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="flex flex-col min-h-screen bg-[#F6F8FA]">
        <header className="sticky top-0 z-50 h-16">
          <Navbar />
        </header>

        <div className="flex flex-1 min-h-0">
          <aside className="hidden md:block w-64 bg-gray-900 text-white sticky top-16 h-[calc(100vh-4rem)] overflow-y-auto">
            <Sidebar />
          </aside>

          <main className="flex-1 overflow-y-auto min-h-0 bg-[#F6F8FA]">
            <div className="max-w-5xl mx-auto px-4">{children}</div>
          </main>
        </div>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
