import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sidebar from "../components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <div className="flex flex-col min-h-screen bg-gray-50">
          {/* Navbar always on top */}
          <header className="sticky top-0 z-50">
            <Navbar />
          </header>

          {/* Main content layout */}
          <div className="flex-1 w-full max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-12 gap-4">
            {/* Sidebar - order 1 on desktop, order 2 on mobile */}
            <aside className="order-2 md:order-1 col-span-12 md:col-span-3">
              <Sidebar />
            </aside>

            {/* Main content - order 1 always on mobile, order 2 on desktop */}
            <main className="order-1 md:order-2 col-span-12 md:col-span-9 px-4">
              {children}
            </main>
          </div>

          {/* Footer at bottom always */}
          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
