import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sidebar from "../components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <div className="flex flex-col min-h-screen bg-gray-50">
          {/* Navbar always on top */}
          <header className="sticky top-0 z-50">
            <Navbar />
          </header>

          {/* Full layout below navbar */}
          <div className="flex flex-1 min-h-0">
            {/* Sidebar fixed to the left */}
            <aside className="w-64 bg-gray-900 text-white hidden md:block h-full sticky top-0">
              <Sidebar />
            </aside>

            {/* Main content */}
            <main className="flex-1">
              <div className="max-w-6xl mx-auto px-4 py-6">{children}</div>
            </main>
          </div>

          {/* Footer at bottom */}
          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
