import AdminSidebar from "@/components/AdminSidebar";
import "../../../app/globals.css";
import { Geist, Geist_Mono } from "next/font/google";

// Load fonts using next/font (SSR safe)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased"   cz-shortcut-listen="true">
        <div className="flex">
          <AdminSidebar />
          <main className="flex-1 bg-gray-100">{children}</main>
        </div>
      </body>
    </html>
  );
}
